### ISSUE TITLE
多音字问题

### ISSUE THREAD

**Issue by waleraye** [viko16/hexo-permalink-pinyin#1]
你好，多音字可以配置生成的拼音吗?
![](https://ws1.sinaimg.cn/large/005xcdLbly1fwa4lfulc9j30e3092t8z.jpg)
比如这样的，生成的是第一个，我想生成第二个，有办法配置吗？

**Comment by waleraye** [comment]
还有一个问题是标签不会生成拼音，访问标签  链接还是带着汉字的
![](https://ws1.sinaimg.cn/large/005xcdLbly1fwa4p0zs8jj309901idfq.jpg)

**Comment by viko16** [comment]
你好，

1. 「多音字可以配置生成的拼音吗?」 理论上是可以的，写法是：
```yaml
permalink_pinyin:
  enable: true
  replace:
    泌: bi
```


2. 「标签不会生成拼音」 的确是的，只能处理 permalink ，因为 hexo 只开放了 `post_permalink` 过滤器
