### ISSUE TITLE
可否添加忽略文章的支持

### ISSUE THREAD

**Issue by imtianx** [viko16/hexo-permalink-pinyin#2]
**问题背景**
> 由于以前文章有些中文命名，在其他地方使用了相关的链接，现在想要开启拼音，那些链接失效，所以想要可以兼容的方式。

**目前用到的简单解决办法**

- 编写脚本，给之前的 md 文件加个前缀，
- 在该插件配置忽略标识符
- 修改插件代码，含有忽略标示符的，去掉忽略符号且不转拼音，

**示例**
对于 `java内存管理.md` 这样的文件需要忽略，先修改文件名为： `ignoree_pinyin_java内存管理.md`

然后，`_config.yml` 中添加忽略标识,如下 `ignore` 字段：

```
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'
  ignore: ignore_pinyin_

```

最后在 插件中进行判断：

```
'use strict';

var slugify = require('transliteration').slugify;
var hexo = hexo || {};
var config = hexo.config || {};
var pluginConfig = config.permalink_pinyin || {};

hexo.extend.filter.register('post_permalink', function (data) {
    if (pluginConfig.enable) {

        // 包含忽略符，则去掉并返回
        if (data.indexOf(pluginConfig.ignore) != -1) {
            return data.replace(pluginConfig.ignore, '')
        }

        // https://github.com/andyhu/transliteration#slugifystr-options
        const options = Object.assign({}, pluginConfig, {ignore: ['/', '.']})
        return slugify(data, options);
    }

    return data;

});


```

> 非常简单粗暴的方法，希望添加支持 :pray:

**Comment by viko16** [comment]
没问题，我把方案扩展成正则如何？

```yaml
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'
  exclude: /^ignore/
```
